# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
ko_fi: StagPoint
custom: ['https://www.paypal.com/donate/?hosted_button_id=HM68G5U43QQZL']
